-- extending icons
reload("lcarv.autocommands")
reload("lcarv.bookmark")
-- reload("lcarv.chatgpt")
reload("lcarv.cmp")
reload("lcarv.colorizer")
reload("lcarv.fidget")
reload("lcarv.git")
reload("lcarv.harpoon")
reload("lcarv.illuminate")
reload("lcarv.inlay-hints")
reload("lcarv.keymaps")
reload("lcarv.lualine")
reload("lcarv.neogit")
reload("lcarv.neoai")
reload("lcarv.neoscroll")
reload("lcarv.numb")
reload("lcarv.options")
reload("lcarv.plugins")
reload("lcarv.scrollbar")
-- reload("lcarv.smoothie")
reload("lcarv.spectre")
reload("lcarv.surround")
reload("lcarv.symbols-outline")
reload("lcarv.telescope")
reload("lcarv.todo-comments")
reload("lcarv.treesitter")
reload("lcarv.whichkey")
reload("lcarv.zen-mode")
reload("lcarv.lsp")

